name: sync
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g: 1.0.0)"
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Set up Git user
        uses: fregante/setup-git-user@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download Flutter SDK v${{ github.event.inputs.version }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: python sync.py ${{ github.event.inputs.version }}
      - name: Download latest Flutter SDK
        if: ${{ github.event_name == 'schedule' }}
        run: python sync.py
